import { CONFIG, periodLabel, nextPeriod, today, dateTimeLabel, money } from "./config.js";
import { Store } from "./store.js";
import { firebaseEnabled, authState, login, logout } from "./firebase.js";
import { formSchema, renderView, renderPeriodModal, esc } from "./views.js";

const $=s=>document.querySelector(s), content=$("#content"), title=$("#pageTitle");
let view="dashboard",period=CONFIG.defaultPeriod,editing=null;
const titles={dashboard:"Panel general",cash:"Caja diaria",providers:"Proveedores",expenses:"Gastos",investments:"Inversiones",people:"Personal",hours:"Horas mensuales",results:"Resultados",compare:"Comparativas",tasks:"Recordatorios",agent:"Agente BLUNNO",closures:"Cierre mensual",files:"Archivos",history:"Historial",import:"Excel / Backup"};
window.__blunnoBranch="General";
const toast=(m,ok=true)=>{const e=$("#toast");e.textContent=m;e.className=`toast show ${ok?'ok':'bad'}`;clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.className='toast',3500)};
function connection(){$("#connectionDot").className=firebaseEnabled?'connected':'local';$("#connectionText").textContent=firebaseEnabled?'Firebase conectado':'Modo local';$("#userText").textContent=firebaseEnabled?'Autenticación habilitada':'Datos guardados en este navegador';}
function refresh(){title.textContent=titles[view];renderView(view,content,period);wire();$("#periodSelector").textContent=periodLabel(period);$("#periodState").textContent=Store.periodIsClosed(period)?'CERRADO':'ABIERTO';$("#periodDot").className=Store.periodIsClosed(period)?'closed':'open';checkReminders();}
function fieldHtml([n,l,t,o],data){let c;if(t==='select'){const opts=(o||[]).map(v=>{const a=Array.isArray(v)?v:[v,v];return `<option value="${esc(a[0])}">${esc(a[1])}</option>`}).join('');c=`<select name="${n}">${opts}</select>`}else if(t==='textarea')c=`<textarea name="${n}" rows="3"></textarea>`;else c=`<input name="${n}" type="${t}" ${t==='number'?'step="0.01" min="0"':''} ${n==='responsible'?'required':''}>`;return `<label class="field">${l}${c}</label>`}
function openModal(type,id=null){const map={provider:'providers',employee:'employees',invoice:'invoices',cash:'cash',hours:'hours',expense:'expenses',investment:'investments',task:'tasks'};editing=id?Store.get(map[type]||type,id):null;const schema=formSchema[type];if(!schema)return;window.__modalType=type;$("#modalKicker").textContent=editing?'EDICIÓN CONTROLADA':'NUEVO REGISTRO';$("#modalTitle").textContent=editing?'Editar registro':'Nuevo registro';$("#formFields").innerHTML=schema.map(x=>fieldHtml(x,editing)).join('')+`<label class="field">Responsable<select name="responsible" required>${CONFIG.responsiblePeople.map(x=>`<option>${x}</option>`).join('')}</select></label>`;for(const [n] of schema){const i=$(`#formFields [name="${n}"]`);if(i&&editing?.[n]!==undefined)i.value=editing[n]}const resp=$('#formFields [name="responsible"]');if(resp&&editing?.responsible)resp.value=editing.responsible;for(const n of ['date','invoiceDate','loadDate']){const d=$(`#formFields [name="${n}"]`);if(d&&!editing)d.value=today()}if(type==='invoice'||type==='provider'){const p=$('#formFields [name="provider"]')||$('#formFields [name="name"]');if(p){p.setAttribute('list','providerNamesModal');const dl=document.createElement('datalist');dl.id='providerNamesModal';Store.list('providers').forEach(x=>{const o=document.createElement('option');o.value=x.name;dl.appendChild(o)});p.parentElement.appendChild(dl)}}$("#modal").classList.remove('hidden');$("#formFields input,#formFields select,#formFields textarea")[0]?.focus()}
function closeModal(){$("#modal").classList.add('hidden');editing=null}
async function save(e){e.preventDefault();const type=e.target.dataset.type,data=Object.fromEntries(new FormData(e.target).entries());try{const numeric=['amount','hours','advance','merchandise','hourlyRate'];numeric.forEach(k=>{if(k in data)data[k]=Number(data[k]||0)});if(['cash','invoice','hours','expense','investment','task'].includes(type))data.period=period;if(type==='invoice'){data.lateMovement=data.lateMovement==='true';data.loadDate=data.loadDate||today();data.responsible=data.responsible||window.__blunnoResponsible||'';if(!data.provider.trim())throw new Error('Elegí o escribí un proveedor.')}if(type==='investment'||type==='expense'||type==='cash'||type==='invoice'||type==='hours')data.responsible=data.responsible||window.__blunnoResponsible||'';const col={provider:'providers',employee:'employees',invoice:'invoices',cash:'cash',hours:'hours',expense:'expenses',investment:'investments',task:'tasks'}[type];if(!col)throw new Error('Tipo inválido.');if(!data.responsible){data.responsible=prompt('¿Quién está cargando este movimiento? (Agus, Nico, Luz o Flor)')||''}if(!data.responsible.trim())throw new Error('El responsable es obligatorio.');if(editing)await Store.update(col,editing.id,data,data.responsible,'Edición desde formulario');else await Store.add(col,data,data.responsible,'Alta desde formulario');closeModal();toast(editing?'Cambios guardados y auditados':'Guardado con éxito');refresh()}catch(err){toast(err.message||'No se pudo guardar',false)}}
function wire(){
 document.querySelectorAll('[data-new]').forEach(b=>b.onclick=()=>openModal(b.dataset.new));
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openModal(b.dataset.edit,b.dataset.id));
 document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{const responsible=prompt('Responsable que confirma la baja:');if(!responsible?.trim())return;try{await Store.remove(b.dataset.delete,b.dataset.id,responsible,'Baja confirmada');toast('El movimiento se encuentra en la papelera.');refresh()}catch(err){toast(err.message,false)}});
 document.querySelectorAll('[data-complete-task]').forEach(b=>b.onclick=async()=>{const responsible=prompt('¿Quién marca la tarea como realizada?');if(!responsible?.trim())return;try{await Store.completeTask(b.dataset.completeTask,responsible);toast('Tarea realizada y guardada en historial.');refresh()}catch(err){toast(err.message,false)}});
 document.querySelectorAll('[data-view-jump]').forEach(b=>b.onclick=()=>{view=b.dataset.viewJump;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));refresh()});
 document.querySelectorAll('.branch-control select').forEach(s=>{s.value=window.__blunnoBranch||'General';s.onchange=()=>{window.__blunnoBranch=s.value;refresh()}});
 document.querySelectorAll('[data-invoice-detail]').forEach(b=>b.onclick=()=>showInvoiceDetail(b.dataset.invoiceDetail));
 const f=$("#recordForm");if(f){f.dataset.type=currentModalType();f.onsubmit=save}
 const closeDetail=$("[data-close-detail]");if(closeDetail)closeDetail.onclick=()=>$("#detailModal").classList.add('hidden');
 const closeBtns=document.querySelectorAll('[data-close-modal]');closeBtns.forEach(b=>b.onclick=closeModal);
 const closeSearch=$("[data-close-search]");if(closeSearch)closeSearch.onclick=()=>$("#searchModal").classList.add('hidden');
 const closeBtn=$("#reminderClose");if(closeBtn)closeBtn.onclick=()=>$("#reminderOverlay").classList.add('hidden');
 const done=$("#reminderDone");if(done)done.onclick=async()=>{const id=done.dataset.id;const responsible=prompt('¿Quién realizó este recordatorio?');if(!responsible?.trim())return;await Store.completeTask(id,responsible);$("#reminderOverlay").classList.add('hidden');toast('Recordatorio realizado.');refresh()};
 const closePeriod=$("#closePeriodButton");if(closePeriod)closePeriod.onclick=async()=>{const responsible=prompt(`Responsable que confirma el cierre de ${periodLabel(period)}:`);if(!responsible?.trim())return;const note=prompt('Observación del cierre (opcional):')||'Cierre manual';if(!confirm(`¿Confirmar cierre de ${periodLabel(period)}?`))return;try{const c=await Store.closePeriod(period,responsible,note);toast(`Cierre guardado como versión ${c.version}.`);refresh()}catch(err){toast(err.message,false)}};
 document.querySelectorAll('[data-print-close]').forEach(b=>b.onclick=()=>printClosure(b.dataset.printClose));
 const exportBackup=$("#exportBackup");if(exportBackup)exportBackup.onclick=()=>Store.exportJson();
 const backup=$("#backupFile");if(backup)backup.onchange=handleBackup;
 const excel=$("#excelFile");if(excel)excel.onchange=handleExcel;
 const send=$("#agentSend");if(send)send.onclick=sendAgent;
 const mic=$("#agentMic");if(mic)mic.onclick=startVoice;
}
function currentModalType(){const titleText=$("#modalTitle")?.textContent||'';if(titleText.toLowerCase().includes('factura'))return'invoice';return window.__modalType||'cash'}
function showInvoiceDetail(id){const x=Store.get('invoices',id);if(!x)return;$("#detailTitle").textContent=`Factura · ${x.provider}`;$("#detailBody").innerHTML=`<div class="detail-grid"><div><span>Monto</span><b>${money(x.amount)}</b></div><div><span>Qué se compró</span><b>${esc(x.item)}</b></div><div><span>Fecha factura</span><b>${x.invoiceDate||'—'}</b></div><div><span>Cargada</span><b>${dateTimeLabel(x.createdAt)}</b></div><div><span>Responsable</span><b>${esc(x.responsible)}</b></div><div><span>Sucursal</span><b>${esc(x.branch)}</b></div></div>`;$("#detailModal").classList.remove('hidden')}
function printClosure(id){const x=Store.get('closures',id);if(!x)return;const s=x.summary;const w=window.open('','_blank');w.document.write(`<html><head><title>BLUNNO Cierre ${x.period} v${x.version}</title><style>body{font-family:Arial;padding:40px;color:#172033}h1{margin-bottom:4px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:25px 0}.card{border:1px solid #ddd;border-radius:10px;padding:14px}.muted{color:#667085}</style></head><body><h1>Distribuidora Blunno</h1><p class="muted">Cierre mensual · ${x.period} · Versión ${x.version}</p><p>Responsable: <b>${esc(x.closedBy)}</b><br>Fecha/hora: <b>${dateTimeLabel(x.closedAt)}</b></p><div class="grid">${Object.entries({Ingresos:s.income,'Caja / otros egresos':s.cashExpense,'Gastos locales':s.localExpense,Inversiones:s.investment,Proveedores:s.provider,Sueldos:s.salary,'Total egresos':s.totalExpenses,Resultado:s.result}).map(([k,v])=>`<div class="card"><b>${k}</b><div>${money(v)}</div></div>`).join('')}</div><p>Observación: ${esc(x.note)}</p><script>window.print()</script></body></html>`);w.document.close()}
function handleBackup(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=async()=>{try{const obj=JSON.parse(r.result),responsible=prompt('Responsable que confirma la restauración:');if(!responsible?.trim())return;await Store.importState(obj,responsible);toast('Backup restaurado.');refresh()}catch(err){toast('Backup inválido.',false)}};r.readAsText(f)}
function parsePlanning(wb,sheet){const ws=wb.Sheets[sheet];const out=[];if(!ws||!ws['!ref'])return out;const range=XLSX.utils.decode_range(ws['!ref']);for(let r=0;r<=range.e.r;r++){const row=[];for(let c=0;c<=range.e.c;c++)row.push(ws[XLSX.utils.encode_cell({r,c})]?.v??'');const name=String(row[0]||'').trim();if(!name||/fecha|día|empleado/i.test(name))continue;for(let c=0;c<range.e.c;c++){const header=String(row[c]||'');const m=header.match(/(\d{1,2})$/);if(!m)continue;const val=ws[XLSX.utils.encode_cell({r:r+1,c})]?.v;if(typeof val==='number')out.push({employee:name,day:Number(m[1]),hours:val})}}return out}
async function handleExcel(e){const f=e.target.files?.[0];if(!f)return;const box=$("#importPreview");box.innerHTML='<div class="loading">Leyendo Excel…</div>';try{const wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:true});box.innerHTML=`<div class="notice success"><b>${esc(f.name)}</b> leído correctamente: ${wb.SheetNames.length} hoja(s).</div>${wb.SheetNames.map((s,i)=>`<div class="sheet-preview"><div><b>${esc(s)}</b><span>Hoja ${i+1}</span></div><button class="secondary-button" data-sync-sheet="${encodeURIComponent(s)}">Analizar / sincronizar</button></div>`).join('')}`;box.querySelectorAll('[data-sync-sheet]').forEach(b=>b.onclick=()=>syncSheet(wb,decodeURIComponent(b.dataset.syncSheet),f.name))}catch(err){box.innerHTML=`<div class="notice danger-box">No se pudo leer el Excel: ${esc(err.message)}</div>`}}
async function syncSheet(wb,sheet,fileName){const responsible=prompt(`Responsable de la sincronización de ${sheet}:`);if(!responsible?.trim())return;try{const blocks=parsePlanning(wb,sheet);let count=0;if(blocks.length){for(const x of blocks){const date=`${period}-${String(x.day).padStart(2,'0')}`;await Store.upsertBySource('hours',`excel-hours|${fileName}|${sheet}|${x.employee}|${date}`,{period,employee:x.employee,branch:window.__blunnoBranch==='General'?'Bodereau':window.__blunnoBranch,date,hours:Number(x.hours||0),sourceFile:fileName},responsible,'Sincronización de horas desde Excel');count++}}else{const ws=wb.Sheets[sheet];const data=XLSX.utils.sheet_to_json(ws,{defval:'',raw:false});for(const r of data){await Store.add('imports',{period,fileName,sheet,row:r,branch:window.__blunnoBranch},responsible,'Importación de hoja Excel');count++}}toast(`Sincronización terminada: ${count} registro(s).`);refresh()}catch(err){toast(err.message||'No se pudo sincronizar',false)}}
function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return toast('El navegador no ofrece dictado por voz. Probá Chrome.',false);const r=new SR();r.lang='es-AR';r.interimResults=false;r.onresult=e=>{$("#agentInput").value=e.results[0][0].transcript};r.onerror=()=>toast('No se pudo tomar el audio.',false);r.start()}
function agentSay(html,who='bot'){const box=$("#agentMessages");if(!box)return;const d=document.createElement('div');d.className=`agent-msg ${who}`;d.innerHTML=html;box.appendChild(d);box.scrollTop=box.scrollHeight}
function parseAmount(text){const m=text.replace(/\./g,'').replace(',','.').match(/(?:\$\s*)?(\d+(?:\.\d+)?)/);return m?Number(m[1]):0}
function parseAgent(text){const t=text.toLowerCase();if(/resumen|gastos de la semana|cuánto gast/.test(t))return{kind:'summary'};if(/crear tarea|recordatorio|recordá|recordar/.test(t)){const title=text.replace(/crear tarea|recordatorio|recordá|recordar/ig,'').trim();return{kind:'task',title:title||'Nueva tarea'};}if(/factura|cargar factura|cargo factura/.test(t)){const provider=(Store.list('providers').map(x=>x.name).find(n=>t.includes(n.toLowerCase().slice(0,4)))||'').trim();return{kind:'invoice',provider,amount:parseAmount(text),item:'Factura cargada desde Agente BLUNNO'};}if(/inversión|inversion|invert/.test(t))return{kind:'investment',amount:parseAmount(text),concept:text};if(/gasto/.test(t))return{kind:'expense',amount:parseAmount(text),concept:text};return{kind:'unknown'};}
async function sendAgent(){const input=$("#agentInput"),text=input.value.trim();if(!text)return;agentSay(esc(text),'user');input.value='';const cmd=parseAgent(text);if(cmd.kind==='summary'){const s=await import('./store.js').then(m=>m.buildSummary(period,window.__blunnoBranch||'General'));agentSay(`En ${periodLabel(period)} y perfil <b>${esc(window.__blunnoBranch||'General')}</b>: ingresos ${money(s.income)}, egresos ${money(s.totalExpenses)}, inversiones ${money(s.investment)} y resultado ${money(s.result)}.`);return}if(cmd.kind==='unknown'){agentSay('Puedo ayudarte con facturas, gastos, inversiones, tareas, recordatorios y resúmenes. Decime la acción y los datos.');return}const pending={...cmd,period,branch:window.__blunnoBranch||'General',responsible:window.__blunnoResponsible||'Nico'};window.__agentPending=pending;agentSay(`<div class="confirm-box"><b>Voy a hacer esto:</b><br>${esc(JSON.stringify(pending,null,2))}<br><button id="agentConfirm" class="primary-button">CONFIRMAR</button> <button id="agentCancel" class="secondary-button">CANCELAR</button></div>`);$("#agentConfirm").onclick=()=>confirmAgent();$("#agentCancel").onclick=()=>{window.__agentPending=null;agentSay('Acción cancelada.')}}
async function confirmAgent(){const p=window.__agentPending;if(!p)return;const responsible=prompt(`Confirmá responsable (${CONFIG.responsiblePeople.join(', ')}):`,p.responsible)||'';if(!responsible.trim())return;try{if(p.kind==='invoice')await Store.add('invoices',{provider:p.provider||prompt('Proveedor:')||'Otros',amount:p.amount||Number(prompt('Monto:')||0),item:p.item,invoiceDate:today(),loadDate:today(),branch:p.branch,period:p.period,responsible},responsible,'Acción confirmada por Agente BLUNNO');else if(p.kind==='expense')await Store.add('expenses',{date:today(),category:'Otros',concept:p.concept,amount:p.amount,branch:p.branch,period:p.period,responsible},responsible,'Acción confirmada por Agente BLUNNO');else if(p.kind==='investment')await Store.add('investments',{date:today(),concept:p.concept,amount:p.amount,branch:p.branch,period:p.period,responsible},responsible,'Acción confirmada por Agente BLUNNO');else if(p.kind==='task')await Store.addTask({title:p.title,dueDate:today(),dueTime:'15:40',responsible,priority:'normal',period:p.period},responsible);agentSay('Listo. La acción quedó guardada y auditada.');window.__agentPending=null;refresh()}catch(err){agentSay(`No se pudo completar: ${esc(err.message)}`)}}
function checkReminders(){const pending=Store.list('tasks').filter(x=>x.status!=='completed');if(!pending.length)return;const nowD=new Date();const due=pending.find(x=>x.dueDate===today()||new Date(`${x.dueDate}T${x.dueTime||'23:59'}`)<nowD);if(!due)return;const overlay=$("#reminderOverlay");$("#reminderTitle").textContent=due.title;$("#reminderMeta").textContent=`📅 ${due.dueDate===today()?'Hoy':due.dueDate} — ${due.dueTime||''} · 👤 ${due.responsible}`;$("#reminderDone").dataset.id=due.id;overlay.classList.remove('hidden')}

$("#newRecordBtn").onclick=()=>{const map={cash:'cash',providers:'invoice',expenses:'expense',investments:'investment',people:'employee',hours:'hours',tasks:'task'};window.__modalType=map[view]||'cash';openModal(window.__modalType)};
$("#mainNav").onclick=e=>{const b=e.target.closest('[data-view]');if(!b)return;view=b.dataset.view;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===b));refresh()};
$("#periodSelector").onclick=()=>{const current=renderPeriodModal();const p=prompt(`Períodos disponibles:\n${current.map(x=>`${x.id} — ${x.status==='closed'?'CERRADO':'ABIERTO'}`).join('\n')}\n\nIngresá YYYY-MM para consultar o crear:`,period);if(!p)return;Store.setPeriod(p.trim());period=p.trim();refresh()};
$("#accountBtn").onclick=()=>{if(!firebaseEnabled)return toast('Firebase no está configurado en este paquete.');$("#loginModal").classList.remove('hidden')};
$("#loginForm").onsubmit=async e=>{e.preventDefault();try{await login($("#loginEmail").value.trim(),$("#loginPassword").value);$("#loginModal").classList.add('hidden');toast('Sesión iniciada');await Store.sync();refresh()}catch(err){$("#loginMessage").textContent=err.message}};
$("#logoutButton").onclick=async()=>{await logout();toast('Sesión cerrada')};
$("#searchBtn").onclick=()=>{$("#searchModal").classList.remove('hidden');$("#searchInput").focus()};
$("#searchInput").oninput=e=>{const q=e.target.value.toLowerCase().trim(),box=$("#searchResults");if(!q){box.innerHTML='<div class="empty-block">Escribí algo para buscar.</div>';return}const src=['providers','employees','invoices','cash','expenses','investments','hours','tasks'].flatMap(c=>Store.list(c).map(x=>({...x,_c:c})));const f=src.filter(x=>JSON.stringify(x).toLowerCase().includes(q)).slice(0,40);box.innerHTML=f.length?f.map(x=>`<div class="search-result"><b>${esc(x.name||x.employee||x.provider||x.title||x.concept||'Registro')}</b><span>${x._c}${x.amount?` · ${money(x.amount)}`:''}</span></div>`).join(''):'<div class="empty-block">Sin resultados.</div>'};
$("#recordForm").addEventListener('submit',save);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();$("#searchModal").classList.add('hidden');$("#detailModal").classList.add('hidden');$("#reminderOverlay").classList.add('hidden')}});
authState(async user=>{if(firebaseEnabled&&user){$("#connectionText").textContent='Firebase conectado';$("#userText").textContent=user.email||'Usuario autenticado';await Store.sync();refresh()}});
connection();refresh();
