import{CONFIG,isFirebaseConfigured,uid,now,today}from'./config.js';import{firebaseAuth,remoteList,remoteAdd,remoteUpdate,remoteDelete,remoteAudit}from'./firebase.js';
const KEY='blunno-control-master-v1';
const collections=['periods','providers','providerEntries','invoices','cash','localExpenses','employees','hours','employeeDebts','liquidations','audit','imports','settings'];
const empty=()=>Object.fromEntries(collections.map(c=>[c,[]]));
const seed=()=>{const s=empty();s.periods=[{id:CONFIG.defaultPeriod,status:'open',name:CONFIG.defaultPeriod}];return s};
let state=load();function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x?{...empty(),...x}:seed()}catch{return seed()}}
const persist=()=>localStorage.setItem(KEY,JSON.stringify(state));const active=n=>(state[n]||[]).filter(x=>!x.deleted);const actor=()=>firebaseAuth?.currentUser?.email||window.__blunnoResponsible||'Usuario local';
const assertResp=n=>{if(!String(n||'').trim())throw new Error('Tenés que indicar quién realiza esta operación.')};
const periodIsClosed=p=>state.periods.some(x=>x.id===p&&x.status==='closed');
async function audit(action,collection,id,before,after,responsible,reason,period=''){const row={id:uid(),action,collection,recordId:id,before:before||null,after:after||null,responsible:responsible||actor(),actor:actor(),at:now(),reason:reason||'',period};state.audit.unshift(row);persist();if(isFirebaseConfigured())await remoteAudit(row)}
async function remoteUpsert(name,row){if(!isFirebaseConfigured())return;await remoteAdd(name,row,row.id)}
async function syncRemote(){if(!isFirebaseConfigured())return;for(const n of collections){try{const rs=await remoteList(n);if(rs.length||n==='periods')state[n]=rs}catch(e){console.warn('Sync',n,e)}}if(!state.periods.length)state.periods=seed().periods;persist()}
function cleanupLocalTrash(){const cut=Date.now()-30*86400000;for(const n of collections){if(n==='audit'||n==='periods'||n==='settings')continue;state[n]=state[n].filter(x=>!x.deleted||new Date(x.deletedAt||0).getTime()>cut)}state.audit=state.audit.filter(x=>x.deletedAt?new Date(x.deletedAt).getTime()>cut:true);persist()}
export const Store={
 get mode(){return isFirebaseConfigured()?'firebase':'local'},get db(){return state},list(name,period=null,opts={}){let r=opts.trash?(state[name]||[]).filter(x=>x.deleted):(state[name]||[]).filter(x=>!x.deleted);if(period&&['cash','hours','invoices','localExpenses','liquidations','providerEntries'].includes(name))r=r.filter(x=>x.period===period);return r},get(name,id,includeDeleted=false){return(state[name]||[]).find(x=>x.id===id&&(!x.deleted||includeDeleted))||null},periodIsClosed,
 setPeriod(p){if(!/^\d{4}-\d{2}$/.test(p))throw new Error('Período inválido.');if(!state.periods.some(x=>x.id===p)){state.periods.push({id:p,status:'open',name:p});persist()}},
 async add(name,data,responsible,reason='Alta manual'){assertResp(responsible);const id=uid(),row={id,...data,deleted:false,createdAt:now(),updatedAt:now()};state[name].unshift(row);persist();await remoteUpsert(name,row);await audit('CREATE',name,id,null,row,responsible,reason,data.period||'');return row},
 async update(name,id,patch,responsible,reason='Edición manual'){assertResp(responsible);const old=this.get(name,id);if(!old)throw new Error('No se encontró el registro.');const row={...old,...patch,updatedAt:now(),deleted:false};state[name]=state[name].map(x=>x.id===id?row:x);persist();if(isFirebaseConfigured())await remoteUpdate(name,id,patch);await audit('UPDATE',name,id,old,row,responsible,reason,row.period||'');return row},
 async remove(name,id,responsible,reason='Baja a papelera'){assertResp(responsible);const old=this.get(name,id);if(!old)return;const row={...old,deleted:true,deletedAt:now(),trashExpiresAt:new Date(Date.now()+30*86400000).toISOString(),updatedAt:now()};state[name]=state[name].map(x=>x.id===id?row:x);persist();if(isFirebaseConfigured())await remoteDelete(name,id);await audit('DELETE',name,id,old,row,responsible,reason,row.period||'')},
 async restore(name,id,responsible){assertResp(responsible);const old=this.get(name,id,true);if(!old)throw new Error('No se encontró el elemento en la papelera.');const row={...old,deleted:false,restoredAt:now(),updatedAt:now()};delete row.deletedAt;delete row.trashExpiresAt;state[name]=state[name].map(x=>x.id===id?row:x);persist();if(isFirebaseConfigured())await remoteUpdate(name,id,{deleted:false,restoredAt:row.restoredAt,deletedAt:null,trashExpiresAt:null});await audit('RESTORE',name,id,old,row,responsible,'Restaurado desde papelera',row.period||'')},
 async trashDeleteNow(name,id,responsible){assertResp(responsible);const old=this.get(name,id,true);if(!old)return;state[name]=state[name].filter(x=>x.id!==id);persist();if(isFirebaseConfigured())await remoteUpdate(name,id,{deleted:true,permanentlyDeleted:true,permanentlyDeletedAt:now()});await audit('PERMANENT_DELETE',name,id,old,null,responsible,'Eliminación definitiva',old.period||'')},
 async upsertBySource(name,sourceKey,data,responsible,reason='Sincronización Excel'){assertResp(responsible);const found=active(name).find(x=>x.sourceKey===sourceKey);return found?this.update(name,found.id,data,responsible,reason):this.add(name,{...data,sourceKey},responsible,reason)},
 async closePeriod(period,next,responsible){assertResp(responsible);const p=state.periods.find(x=>x.id===period)||{id:period,status:'open'};const closed={...p,status:'closed',closedAt:now(),closedBy:responsible};state.periods=state.periods.filter(x=>x.id!==period);state.periods.push(closed);if(!state.periods.some(x=>x.id===next))state.periods.push({id:next,status:'open',name:next});persist();if(isFirebaseConfigured()){await remoteAdd('periods',closed,period);await remoteAdd('periods',{id:next,status:'open',name:next},next)}await audit('CLOSE_PERIOD','periods',period,p,closed,responsible,`Apertura de ${next}`,period)},
 async sync(){await syncRemote();cleanupLocalTrash()},exportJson(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`blunno-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)},async importState(obj,responsible){assertResp(responsible);const before=state;state={...empty(),...obj};persist();await audit('IMPORT_STATE','system','backup',before,state,responsible,'Restauración de backup')}
};
