import { CONFIG, money, number, dateLabel, dateTimeLabel, periodLabel, daysInPeriod, isoDate, prevPeriod, today } from "./config.js";
import { Store } from "./store.js";

export const esc = v => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const rows = (name, period, branch) => Store.list(name, period, branch);
const kpi = (label, value, hint="", cls="") => `<article class="kpi ${cls}"><span>${esc(label)}</span><strong>${value}</strong><small>${esc(hint)}</small></article>`;
const table = (headers, body, empty="No hay registros para mostrar.") => {
 const hasSelection=String(body||'').includes('data-bulk-select=');
 const collection=(String(body||'').match(/data-bulk-select="([^"]+)"/)||[])[1]||'';
 const head=hasSelection?['<input type="checkbox" title="Seleccionar todo" data-bulk-select-all="'+esc(collection)+'">',...headers]:headers;
 const toolbar=hasSelection?`<div class="bulk-toolbar"><span>Seleccioná movimientos para operar en conjunto.</span><button class="danger-button" data-bulk-delete="${esc(collection)}">Enviar seleccionados a papelera</button></div>`:'';
 return `${toolbar}<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${body || `<tr><td colspan="${head.length}" class="empty">${empty}</td></tr>`}</tbody></table></div>`;
};
const actions = (collection,id,editType=collection) => {
 const readOnly = typeof window !== "undefined" && window.__blunnoBranch === "General" && ["invoices","cash","expenses","investments","employees","hours","incomes"].includes(collection);
 if (readOnly) return `<div class="row-actions"><button class="secondary-button compact-button" data-detail="${esc(collection)}" data-id="${esc(id)}">Ver</button></div>`;
 return `<div class="row-actions"><input type="checkbox" aria-label="Seleccionar" data-bulk-select="${esc(collection)}" data-id="${esc(id)}"><button data-edit="${editType}" data-id="${esc(id)}">Editar</button><button class="danger-link" data-delete="${collection}" data-id="${esc(id)}">Papelera</button></div>`;
};
const branchFilter = branch => CONFIG.profiles.map(x=>`<button class="filter-chip ${x===branch?'active':''}" data-profile="${x}">${x}</button>`).join("");

export const formSchema = {
  cash: [
    ["date","Fecha","date"],["branch","Sucursal","select",CONFIG.branches],
    ["type","Tipo","select",[["income","Ingreso"],["expense","Gasto de caja"],["payment","Pago"]]],
    ["concept","Concepto","text"],["amount","Importe","number"],["expected","Importe esperado","number"],
    ["notes","Observaciones","textarea"],["lateMovement","Movimiento tardío","checkbox"]
  ],
  provider: [["name","Proveedor","text"]],
  invoice: [
    ["provider","Proveedor","text"],["number","N° de factura","text"],["operationDate","Fecha del movimiento","date"],
    ["loadDate","Fecha de carga","date"],["branch","Sucursal","select",CONFIG.branches],
    ["amount","Importe","number"],["notes","Observaciones","textarea"],["lateMovement","Carga tardía de período cerrado","checkbox"]
  ],
  income: [
    ["date","Fecha","date"],["branch","Sucursal","select",CONFIG.branches],["concept","Origen / concepto","text"],
    ["amount","Importe","number"],["notes","Detalle","textarea"],["lateMovement","Movimiento tardío","checkbox"]
  ],
  expense: [
    ["date","Fecha","date"],["branch","Sucursal","select",CONFIG.branches],["category","Categoría","select",CONFIG.expenseCategories],
    ["concept","Detalle / resumen","text"],["amount","Importe","number"],["document","Comprobante / referencia","text"],["notes","Observaciones","textarea"],
    ["lateMovement","Movimiento tardío","checkbox"]
  ],
  investment: [
    ["date","Fecha","date"],["branch","Sucursal","select",CONFIG.branches],["concept","Resumen de la inversión","text"],
    ["amount","Importe","number"],["document","Comprobante / referencia","text"],["notes","Detalle","textarea"],["lateMovement","Movimiento tardío","checkbox"]
  ],
  employee: [["name","Nombre completo","text"],["branch","Sucursal","select",CONFIG.branches],["role","Puesto","text"],["hourlyRate","Valor hora actual","number"],["active","Estado","select",[["true","Activo"],["false","Inactivo"]]]],
  hours: [["employee","Empleado","text"],["date","Fecha","date"],["hours","Horas","number"],["advance","Adelanto / vale","number"],["merchandise","Mercadería","number"],["holiday","Feriado","select",[["no","No"],["yes","Sí"]]],["notes","Observaciones","textarea"]],
  task: [["title","Tarea / recordatorio","text"],["dueDate","Fecha","date"],["dueTime","Hora","time"],["priority","Prioridad","select",[["normal","Normal"],["high","Alta"],["urgent","Urgente"]]],["responsible","Responsable","select",CONFIG.responsiblePeople],["repeat","Repetición","select",[["none","Sin repetición"],["daily","Diaria"],["weekly","Semanal"],["monthly","Mensual"]]],["notes","Notas","textarea"]]
};

export function renderDashboard(content, period, branch="General") {
  const s=Store.summary(period,branch), prev=Store.summary(prevPeriod(period),branch);
  const pct=(a,b)=>a===0?(b===0?0:100):((b-a)/Math.abs(a))*100;
  const alerts=[];
  if(s.income===0) alerts.push("No hay ingresos independientes cargados para el período seleccionado.");
  const tasks=Store.list("tasks").filter(x=>x.status!=="completed").sort((a,b)=>`${a.dueDate} ${a.dueTime}`.localeCompare(`${b.dueDate} ${b.dueTime}`)).slice(0,4);
  const detailButton=(kind,label,value,hint)=>`<button class="kpi kpi-click" data-dashboard-detail="${kind}"><span>${esc(label)}</span><strong>${value}</strong><small>${esc(hint)}</small></button>`;
  content.innerHTML=`
    <div class="profile-bar"><div><span class="section-kicker">PERFIL DE TRABAJO</span><b>${esc(branch)}</b><small>${branch==='General'?'Vista consolidada: no mezcla ni modifica las sucursales.':'Los valores se filtran exclusivamente a esta sucursal.'}</small></div><div class="profile-chips">${branchFilter(branch)}</div></div>
    <section class="hero"><div><span class="hero-tag">CENTRO DE CONTROL BLUNNO</span><h2>Todo el negocio, ordenado y trazable.</h2><p>${periodLabel(period)} · ${esc(branch)} · cada cambio queda auditado.</p><div class="hero-actions"><button class="primary-button" data-view-jump="close">Preparar cierre</button><button class="secondary-button" data-view-jump="agent">Abrir Agente BLUNNO</button><button class="secondary-button" data-pdf-close="dashboard">PDF del resumen</button></div></div><img src="distri.jpeg" alt="Distribuidora Blunno"></section>
    <div class="kpi-grid">${detailButton("income","Ingresos",money(s.income),`${Store.list('incomes',period,branch).length} movimientos independientes`)}${detailButton("expenses","Gastos del local",money(s.localExpense),`${s.expenseCount} movimientos`)}${detailButton("providers","Proveedores",money(s.providers),`${s.invoiceCount} facturas cargadas`)}${detailButton("investments","Inversiones",money(s.investment),`${s.investmentCount} movimientos`)}${detailButton("salary","Personal",money(s.salary),`${s.liquidationCount} liquidaciones / horas`)}${detailButton("result","Resultado",money(s.result),"Sin incluir Caja diaria")}</div>
    <div class="grid-2"><section class="panel"><div class="panel-head"><div><span class="section-kicker">VARIACIÓN</span><h3>Contra ${periodLabel(prevPeriod(period))}</h3></div></div>${metricLine("Ingresos",prev.income,s.income,pct(prev.income,s.income))}${metricLine("Gastos del local",prev.localExpense,s.localExpense,pct(prev.localExpense,s.localExpense))}${metricLine("Resultado",prev.result,s.result,pct(prev.result,s.result))}</section><section class="panel"><div class="panel-head"><div><span class="section-kicker">CONTROL</span><h3>Alertas y pendientes</h3></div></div>${alerts.length?alerts.map(a=>`<div class="alert-row warning">⚠ ${esc(a)}</div>`).join(''):'<div class="alert-row success">✓ No hay alertas críticas detectadas.</div>'}${tasks.map(t=>`<div class="task-mini"><b>${esc(t.title)}</b><span>${dateLabel(t.dueDate)} ${esc(t.dueTime||'')} · ${esc(t.responsible)}</span></div>`).join('')}</section></div>
  `;
}

function metricLine(label,a,b,p){return `<div class="metric-line"><div><b>${esc(label)}</b><span>${money(a)} → ${money(b)}</span></div><strong class="${p>=0?'up':'down'}">${p>=0?'+':''}${p.toFixed(1)}%</strong></div>`}

export function renderCash(content,period,branch="General"){
 const data=rows("cash",period,branch);
 const days=daysInPeriod(period);
 const weeks=Math.max(1,Math.ceil(days/7));
 const rawIndex=Number(localStorage.getItem(`blunno-cash-week-${period}-${branch}`)||0);
 const weekIndex=Math.min(Math.max(rawIndex,0),weeks-1);
 const startDay=weekIndex*7+1, endDay=Math.min(startDay+6,days), weekDays=Array.from({length:endDay-startDay+1},(_,i)=>startDay+i);
 const opening=getOpeningForView(period,branch);
 const conceptsByType={income:[...new Set([...CONFIG.cashIncomeConcepts,...data.filter(x=>x.type==='income').map(x=>x.concept||'Sin concepto')])],expense:[...new Set([...CONFIG.cashExpenseConcepts,...data.filter(x=>x.type==='expense').map(x=>x.concept||'Sin concepto')])],payment:[...new Set([...CONFIG.cashPaymentConcepts,...data.filter(x=>x.type==='payment').map(x=>x.concept||'Pagos')])]};
 const dayTotals=Array.from({length:days},(_,i)=>{const d=i+1,date=isoDate(period,d);const inc=data.filter(x=>x.type==='income'&&x.date===date&&!/^saldo\s+d[ií]a\s+anterior$/i.test(String(x.concept||''))).reduce((s,x)=>s+Number(x.amount||0),0),exp=data.filter(x=>x.type==='expense'&&x.date===date).reduce((s,x)=>s+Number(x.amount||0),0),pay=data.filter(x=>x.type==='payment'&&x.date===date).reduce((s,x)=>s+Number(x.amount||0),0);return {d,date,inc,exp,pay}});
 let saldo=opening; dayTotals.forEach(x=>{x.opening=saldo;x.available=saldo+x.inc;x.rest=x.available-x.exp-x.pay;saldo=x.rest});
 const kindTitle={income:'Ingresos',expense:'Gastos de caja',payment:'Pagos'};
 const matrix=(type)=>`<section class="panel cash-matrix-panel"><div class="panel-head"><div><span class="section-kicker">${type==='income'?'INGRESOS':type==='expense'?'GASTOS DE CAJA':'PAGOS'}</span><h3>${kindTitle[type]}</h3></div>${branch!=='General'?`<button class="secondary-button" data-cash-add-row="${type}">＋ Agregar concepto</button>`:''}</div><div class="sheet-wrap"><table class="matrix-table cash-main-matrix"><thead><tr><th class="sticky-col">Concepto</th>${weekDays.map(d=>{const dt=new Date(`${isoDate(period,d)}T12:00:00`);return `<th>${dt.toLocaleDateString('es-AR',{weekday:'short'}).replace('.','')}<small>${d}</small></th>`}).join('')}<th>TOTAL</th></tr></thead><tbody>${conceptsByType[type].map(c=>`<tr><th class="sticky-col">${esc(c)}</th>${weekDays.map(d=>{const date=isoDate(period,d),r=data.find(q=>q.type===type&&q.date===date&&(q.concept||'Sin concepto')===c);const carry=type==='income'&&/^saldo\s+d[ií]a\s+anterior$/i.test(String(c||''));const carryValue=dayTotals[d-1]?.opening||0;return `<td data-cash-cell data-type="${type}" data-concept="${esc(c)}" data-date="${date}"><input inputmode="decimal" ${branch==='General'||carry?'disabled':''} value="${carry?esc(carryValue):r?esc(r.amount):''}" placeholder="—" title="${carry?'Calculado automáticamente desde el resto del día anterior':''}"></td>`}).join('')}<td class="total-cell">${type==='income'&&/^saldo\s+d[ií]a\s+anterior$/i.test(String(c||''))?'—':money(weekDays.reduce((sum,d)=>sum+Number(data.find(q=>q.type===type&&q.date===isoDate(period,d)&&(q.concept||'Sin concepto')===c)?.amount||0),0))}</td></tr>`).join('')||`<tr><td colspan="${weekDays.length+2}" class="empty">No hay conceptos definidos.</td></tr>`}</tbody><tfoot><tr><th class="sticky-col">TOTAL</th>${weekDays.map(d=>`<th>${money(dayTotals[d-1][type==='income'?'inc':type==='expense'?'exp':'pay'])}</th>`).join('')}<th>${money(weekDays.reduce((sum,d)=>sum+Number(dayTotals[d-1][type==='income'?'inc':type==='expense'?'exp':'pay']),0))}</th></tr></tfoot></table></div></section>`;
 content.innerHTML=`<div class="profile-bar"><div><span class="section-kicker">CAJA DIARIA · CUADRO OPERATIVO</span><b>${esc(branch)}</b><small>Control físico de dinero. No alimenta el resultado económico. Semana ${weekIndex+1} de ${weeks} · días ${startDay}–${endDay}.</small></div><div class="profile-chips">${branchFilter(branch)}</div></div>
 <div class="cash-week-nav"><button class="secondary-button" data-cash-week="prev" ${weekIndex===0?'disabled':''}>← Semana anterior</button><strong>Semana ${weekIndex+1} · ${dateLabel(isoDate(period,startDay))} al ${dateLabel(isoDate(period,endDay))}</strong><button class="secondary-button" data-cash-week="next" ${weekIndex===weeks-1?'disabled':''}>Semana siguiente →</button></div>
 <div class="cash-topbar"><div><span>Saldo inicial del período</span><strong>${money(opening)}</strong><small>El resto de cada día pasa automáticamente al siguiente.</small></div>${branch!=='General'?`<button id="cashOpeningButton" class="secondary-button">Editar saldo inicial</button>`:''}<button class="secondary-button" data-pdf-close="cash">Generar PDF</button></div>
 <div class="mini-kpis">${kpi('Ingresos',money(dayTotals.reduce((s,x)=>s+x.inc,0)),'Período')}${kpi('Gastos',money(dayTotals.reduce((s,x)=>s+x.exp,0)),'Período')}${kpi('Pagos',money(dayTotals.reduce((s,x)=>s+x.pay,0)),'Período')}${kpi('Resto final',money(saldo),'Saldo que arranca el siguiente día')}</div>
 ${matrix('income')}${matrix('expense')}${matrix('payment')}
 <section class="panel"><div class="panel-head"><div><span class="section-kicker">CONTROL DIARIO</span><h3>Saldo anterior + ingresos − gastos − pagos = resto</h3></div></div><div class="table-wrap"><table class="matrix-table"><thead><tr><th>Día</th>${weekDays.map(d=>`<th>${d}</th>`).join('')}</tr></thead><tbody><tr><th>SALDO ANTERIOR</th>${weekDays.map(d=>`<td>${money(dayTotals[d-1].opening)}</td>`).join('')}</tr><tr><th>INGRESOS</th>${weekDays.map(d=>`<td>${money(dayTotals[d-1].inc)}</td>`).join('')}</tr><tr><th>PLATA DISPONIBLE</th>${weekDays.map(d=>`<td>${money(dayTotals[d-1].available)}</td>`).join('')}</tr><tr><th>GASTOS</th>${weekDays.map(d=>`<td>${money(dayTotals[d-1].exp)}</td>`).join('')}</tr><tr><th>PAGOS</th>${weekDays.map(d=>`<td>${money(dayTotals[d-1].pay)}</td>`).join('')}</tr><tr class="total-row"><th>RESTO</th>${weekDays.map(d=>`<td>${money(dayTotals[d-1].rest)}</td>`).join('')}</tr></tbody></table></div></section>`;
}

function getOpeningForView(period,branch){return Number(Store.db.settings.find(x=>x.id===`cash-opening-${period}-${branch}`)?.amount||0)}

export function renderIncome(content,period,branch="General"){ const data=rows('incomes',period,branch).sort((a,b)=>String(b.date).localeCompare(String(a.date))); const total=data.reduce((s,x)=>s+Number(x.amount||0),0); content.innerHTML=`<div class="profile-bar"><div><span class="section-kicker">INGRESOS</span><b>${esc(branch)}</b><small>Ingresos del negocio separados de Caja diaria.</small></div><div class="profile-chips">${branchFilter(branch)}</div></div><div class="page-intro"><div><h2>Ingresos</h2><p>Estos importes son los que alimentan el indicador Ingresos de la página principal. Caja diaria queda completamente separada.</p></div><button class="secondary-button" data-pdf-close="income">PDF</button><button class="primary-button" data-new="income">＋ Nuevo ingreso</button></div><div class="mini-kpis">${kpi('Total',money(total))}${kpi('Movimientos',data.length)}</div>${table(['Fecha','Medio','Concepto','Sucursal','Importe','Acciones'],data.map(x=>`<tr><td>${dateLabel(x.date)}</td><td>${esc(x.method||'—')}</td><td><b>${esc(x.concept||'Sin concepto')}</b></td><td>${esc(x.branch)}</td><td>${money(x.amount)}</td><td>${actions('incomes',x.id,'income')}</td></tr>`).join(''))}` }

export function renderProviders(content,period,branch="General"){
 const data=rows('providers').sort((a,b)=>String(a.name).localeCompare(String(b.name),'es')); const invoices=rows('invoices',period,branch);
 const totals=new Map(); invoices.forEach(x=>totals.set(x.provider,(totals.get(x.provider)||0)+Number(x.amount||0)));
 const days=daysInPeriod(period); const matrix=data.map(p=>{const cells=Array.from({length:days},(_,i)=>{const date=isoDate(period,i+1);const v=invoices.filter(x=>x.provider===p.name&&(x.operationDate||x.date)===date).reduce((s,x)=>s+Number(x.amount||0),0);return `<td>${v?money(v):'—'}</td>`}).join('');return `<tr><th class="sticky-col"><b>${esc(p.name)}</b></th>${cells}<td class="total-cell">${money(totals.get(p.name)||0)}</td></tr>`}).join('');
 content.innerHTML=`<div class="profile-bar"><div><span class="section-kicker">MAESTRO PERMANENTE</span><b>Proveedores</b><small>Los nombres permanecen entre meses. Las facturas son movimientos independientes.</small></div><div class="profile-chips">${branchFilter(branch)}</div></div><div class="page-intro"><div><h2>Proveedores</h2><p>Escribí parte del nombre al cargar una factura y completamos la coincidencia.</p></div><button class="secondary-button" data-pdf-close="providers">PDF</button><button class="primary-button" data-new="provider">＋ Nuevo proveedor</button></div>${table(['Proveedor','Facturado en período','Estado','Acciones'],data.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${money(totals.get(x.name)||0)}</td><td><span class="status-pill ${x.active===false?'muted':''}">${x.active===false?'INACTIVO':'ACTIVO'}</span></td><td>${actions('providers',x.id,'provider')}<button class="secondary-button compact-button" data-provider-history="${esc(x.name)}">Historial</button></td></tr>`).join(''))}<section class="panel"><div class="panel-head"><div><span class="section-kicker">PLANILLA</span><h3>Proveedor × día · ${periodLabel(period)}</h3></div></div><div class="sheet-wrap"><table class="hours-sheet provider-matrix"><thead><tr><th class="sticky-col">Proveedor</th>${Array.from({length:days},(_,i)=>`<th>${i+1}</th>`).join('')}<th>TOTAL</th></tr></thead><tbody>${matrix}</tbody></table></div></section>`;
}

export function renderInvoices(content,period,branch="General"){
 const data=rows('invoices',period,branch).sort((a,b)=>String(b.operationDate||b.date).localeCompare(String(a.operationDate||a.date))); const total=data.reduce((s,x)=>s+Number(x.amount||0),0);
 content.innerHTML=`<div class="profile-bar"><div><span class="section-kicker">FACTURAS · CARGA Y CONTROL</span><b>${esc(branch)}</b><small>Solo cargamos la factura. No hay estado de pago ni vencimiento: una factura cargada queda marcada en verde como CARGADA.</small></div><div class="profile-chips">${branchFilter(branch)}</div></div><section class="panel quick-invoice"><div class="panel-head"><div><span class="section-kicker">CARGA EXPRESS</span><h3>Una factura en segundos</h3></div></div>${branch==='General'?`<div class="notice warning">Elegí una sucursal concreta arriba para cargar facturas.</div>`:`<div class="quick-invoice-grid"><input id="quickInvoiceProvider" list="providerList" placeholder="Proveedor"><input id="quickInvoiceNumber" placeholder="N° factura"><input id="quickInvoiceDate" type="date" value="${today()}"><input id="quickInvoiceAmount" inputmode="decimal" placeholder="Importe"><button class="primary-button" data-invoice-quick-save>Guardar factura</button></div><div class="quick-hint">Ejemplo: Aguilera · 0001-00012345 · fecha · $ 125.000</div>`}</section><div class="page-intro"><div><h2>Facturas</h2><p>Cada factura conserva fecha de movimiento, fecha de carga, sucursal, responsable y auditoría. La misma numeración puede repetirse en distintas sucursales.</p></div><button class="secondary-button" data-pdf-close="invoices">PDF</button></div><div class="mini-kpis">${kpi('Total',money(total))}${kpi('Documentos',data.length)}${kpi('Proveedores con facturas',new Set(data.map(x=>x.provider)).size)}</div>${table(['Proveedor','Factura','Movimiento','Carga','Sucursal','Importe','Estado','Acciones'],data.map(x=>`<tr><td><b>${esc(x.provider)}</b></td><td>${esc(x.number||'—')}</td><td>${dateLabel(x.operationDate||x.date)}</td><td>${dateTimeLabel(x.loadDate||x.createdAt)}</td><td>${esc(x.branch)}</td><td class="amount clickable" data-detail="invoices" data-id="${x.id}">${money(x.amount)}</td><td><span class="status-pill success">CARGADA</span></td><td>${actions('invoices',x.id)}</td></tr>`).join(''))}`;
}

export function renderExpenses(content,period,branch="General"){
 const data=rows('expenses',period,branch).sort((a,b)=>String(b.date).localeCompare(String(a.date))); const total=data.reduce((s,x)=>s+Number(x.amount||0),0); const cats=CONFIG.expenseCategories.map(c=>[c,data.filter(x=>x.category===c).reduce((s,x)=>s+Number(x.amount||0),0)]).filter(x=>x[1]);
 content.innerHTML=`<div class="profile-bar"><div><span class="section-kicker">GASTOS DEL LOCAL</span><b>${esc(branch)}</b><small>Categorías basadas en la estructura de tus planillas.</small></div><div class="profile-chips">${branchFilter(branch)}</div></div><div class="page-intro"><div><h2>Gastos por categoría</h2><p>Proveedores y gastos del local se mantienen separados.</p></div><button class="secondary-button" data-pdf-close="expenses">PDF</button><button class="primary-button" data-new="expense">＋ Nuevo gasto</button></div><div class="mini-kpis">${kpi('Total gastos',money(total))}${kpi('Movimientos',data.length)}${kpi('Categorías usadas',cats.length)}</div><div class="category-cards">${cats.map(([c,v])=>`<div class="category-card"><span>${esc(c)}</span><strong>${money(v)}</strong></div>`).join('')||'<div class="empty-block">Todavía no hay gastos por categoría.</div>'}</div>${table(['Fecha','Categoría','Detalle','Sucursal','Importe','Responsable','Acciones'],data.map(x=>`<tr><td>${dateLabel(x.date)}</td><td><b>${esc(x.category)}</b></td><td>${esc(x.concept)}</td><td>${esc(x.branch)}</td><td class="amount">${money(x.amount)}</td><td>${esc(x.responsible)}</td><td>${actions('expenses',x.id)}</td></tr>`).join(''))}`;
}

export function renderInvestments(content,period,branch="General"){
 const data=rows('investments',period,branch).sort((a,b)=>String(b.date).localeCompare(String(a.date))); const total=data.reduce((s,x)=>s+Number(x.amount||0),0);
 content.innerHTML=`<div class="profile-bar"><div><span class="section-kicker">GASTOS DE INVERSIÓN</span><b>${esc(branch)}</b><small>Cada sucursal conserva su propia cuenta; General consolida sin mezclar registros.</small></div><div class="profile-chips">${branchFilter(branch)}</div></div><div class="page-intro"><div><h2>Inversiones</h2><p>Resumen, importe, fecha, responsable y comprobante quedan registrados.</p></div><button class="secondary-button" data-pdf-close="investments">PDF</button><button class="primary-button" data-new="investment">＋ Nueva inversión</button></div><div class="mini-kpis">${kpi('Invertido',money(total))}${kpi('Movimientos',data.length)}</div>${table(['Fecha','Resumen','Sucursal','Importe','Comprobante','Responsable','Acciones'],data.map(x=>`<tr><td>${dateLabel(x.date)}</td><td><b>${esc(x.concept)}</b><small class="cell-note">${esc(x.notes||'')}</small></td><td>${esc(x.branch)}</td><td class="amount">${money(x.amount)}</td><td>${esc(x.document||'—')}</td><td>${esc(x.responsible)}</td><td>${actions('investments',x.id)}</td></tr>`).join(''))}`;
}

export function renderPeople(content,period,branch="General"){
 const data=rows('employees').filter(x=>branch==='General'||x.branch===branch);
 content.innerHTML=`<div class="profile-bar"><div><span class="section-kicker">PERSONAL</span><b>${esc(branch)}</b><small>Las fichas pertenecen a una sucursal y no se mezclan.</small></div><div class="profile-chips">${branchFilter(branch)}</div></div><div class="page-intro"><div><h2>Personal</h2><p>Valor hora individual, estado y sucursal.</p></div><button class="secondary-button" data-pdf-close="people">PDF</button><button class="primary-button" data-new="employee">＋ Nuevo empleado</button></div>${table(['Empleado','Sucursal','Puesto','Valor hora','Estado','Acciones'],data.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.branch)}</td><td>${esc(x.role||'—')}</td><td>${money(x.hourlyRate)}</td><td><span class="status-pill ${x.active===false?'muted':''}">${x.active===false?'INACTIVO':'ACTIVO'}</span></td><td>${actions('employees',x.id,'employee')}</td></tr>`).join(''))}`;
}

function weekCells(period,employee,branch){const days=daysInPeriod(period);let html='';for(let d=1;d<=days;d++){const date=isoDate(period,d), r=Store.list('hours',period,branch).find(x=>x.employeeId===employee.id&&x.date===date);const dow=new Date(`${date}T12:00:00`).toLocaleDateString('es-AR',{weekday:'short'}).replace('.','');html+=`<td class="hour-cell" data-hour-date="${date}" data-employee="${employee.id}"><span>${dow}</span><input inputmode="decimal" value="${r?esc(r.hours):''}" placeholder="–" data-hour-input></td>`}return html;}

export function renderHours(content,period,branch="General"){
 const allEmployees=Store.list('employees').filter(e=>e.active!==false && (branch==='General'||e.branch===branch)).sort((a,b)=>a.name.localeCompare(b.name,'es')); const savedEmployee=localStorage.getItem('blunno-hours-employee')||'ALL'; const selectedEmployee=allEmployees.some(e=>e.id===savedEmployee)?savedEmployee:'ALL'; const employees=allEmployees.filter(e=>selectedEmployee==='ALL'||e.id===selectedEmployee);
 const data=Store.list('hours',period,branch); const days=daysInPeriod(period);
 const totalFor=e=>data.filter(x=>x.employeeId===e.id).reduce((s,x)=>s+Number(x.hours||0),0);
 const value=e=>{const r=data.filter(x=>x.employeeId===e.id);return {hours:r.reduce((s,x)=>s+Number(x.hours||0),0),advance:r.reduce((s,x)=>s+Number(x.advance||0),0),merch:r.reduce((s,x)=>s+Number(x.merchandise||0),0),holiday:r.filter(x=>x.holiday==='yes').reduce((s,x)=>s+Number(x.hours||0),0)}};
 const weeks=[]; for(let start=1;start<=days;start+=7) weeks.push({start,end:Math.min(start+6,days)});
 const grid=employees.map(e=>{const v=value(e); const weekCells=weeks.map(w=>`<td class="week-total">${number(data.filter(x=>x.employeeId===e.id&&Number(x.date.slice(-2))>=w.start&&Number(x.date.slice(-2))<=w.end).reduce((s,x)=>s+Number(x.hours||0),0))}</td>`).join(''); return `<tr><th class="sticky-col employee-sticky"><b>${esc(e.name)}</b><small>${esc(e.branch||'Sin asignar')}</small></th>${Array.from({length:days},(_,i)=>{const d=i+1,date=isoDate(period,d),x=data.find(r=>r.employeeId===e.id&&r.date===date);const cls=x?.holiday==='yes'?'holiday-cell':x?.status==='franco'?'franco-cell':'';return `<td class="${cls}" data-hour-date="${date}" data-employee="${e.id}" data-hour-cell><input class="hour-cell-input" value="${esc(x?.displayValue??x?.hours??'')}" placeholder="—" inputmode="decimal" title="Número de horas · F = franco · H = feriado"></td>`}).join('')}${weekCells}<td class="total-cell">${number(v.hours)}</td><td><button class="cell-edit-button" data-hours-adjust="advance" data-employee-adjust="${e.id}">${money(v.advance)}</button></td><td><button class="cell-edit-button" data-hours-adjust="merchandise" data-employee-adjust="${e.id}">${money(v.merch)}</button></td><td>${number(v.holiday)}</td><td><button class="primary-button compact-button" data-liquidate="${e.id}">Totalizar</button></td></tr>`}).join('');
 const footer=Array.from({length:days},(_,i)=>{const d=i+1;return `<th>${number(data.filter(x=>x.date===isoDate(period,d)).reduce((s,x)=>s+Number(x.hours||0),0))}</th>`}).join('');
 content.innerHTML=`<div class="profile-bar"><div><span class="section-kicker">HORAS MENSUALES · PLANILLA</span><b>${esc(branch)}</b><small>La estructura replica la lógica del Excel: días directos, totales, adelantos, mercadería y feriados. En una celda: número = horas, F = franco, H = feriado (conserva las horas o usa 8 si está vacía).</small></div><div class="profile-chips">${branchFilter(branch)}</div></div>
 <div class="hours-toolbar"><div><b>${periodLabel(period)}</b><span>${employees.length} empleados visibles · ${number(data.reduce((s,x)=>s+Number(x.hours||0),0))} horas cargadas</span></div><div><label class="hours-filter">Empleado<select id="hoursEmployeeFilter"><option value="ALL" ${selectedEmployee==='ALL'?'selected':''}>Todos los empleados</option>${allEmployees.map(e=>`<option value="${e.id}" ${selectedEmployee===e.id?'selected':''}>${esc(e.name)}</option>`).join('')}</select></label><button class="secondary-button" data-hours-focus="first">Ir a primera celda</button><button class="secondary-button" data-pdf-close="hours">PDF</button><button class="primary-button" data-new="hours">＋ Carga manual</button></div></div>
 <section class="panel hours-panel"><div class="sheet-wrap hours-sheet"><table class="matrix-table"><thead><tr><th class="sticky-col employee-sticky">Empleado</th>${Array.from({length:days},(_,i)=>{const d=i+1,dt=new Date(`${isoDate(period,d)}T12:00:00`);return `<th>${dt.toLocaleDateString('es-AR',{weekday:'short'}).replace('.','')}<small>${d}</small></th>`}).join('')}${weeks.map((w,i)=>`<th>SEM ${i+1}<small>${w.start}-${w.end}</small></th>`).join('')}<th>HORAS</th><th>ADELANTOS</th><th>MERCADERÍA</th><th>FERIADO</th><th>LIQ.</th></tr></thead><tbody>${grid||`<tr><td colspan="${days+weeks.length+6}" class="empty">No hay empleados asignados a ${esc(branch)}.</td></tr>`}</tbody><tfoot><tr><th class="sticky-col">TOTAL DÍA</th>${footer}${weeks.map(w=>`<th>${number(data.filter(x=>Number(x.date.slice(-2))>=w.start&&Number(x.date.slice(-2))<=w.end).reduce((s,x)=>s+Number(x.hours||0),0))}</th>`).join('')}<th>${number(data.reduce((s,x)=>s+Number(x.hours||0),0))}</th><th>${money(data.reduce((s,x)=>s+Number(x.advance||0),0))}</th><th>${money(data.reduce((s,x)=>s+Number(x.merchandise||0),0))}</th><th>${number(data.filter(x=>x.holiday==='yes').reduce((s,x)=>s+Number(x.hours||0),0))}</th><th>—</th></tr></tfoot></table></div></section>
 <section class="panel"><div class="panel-head"><div><span class="section-kicker">REFERENCIA DE CARGA</span><h3>Valores permitidos en la celda</h3></div></div><div class="legend-row"><span><b>8</b> horas</span><span><b>F</b> / <b>franco</b> descanso</span><span><b>H</b> marca feriado y calcula con tarifa feriado</span><span>Enter guarda y avanza</span></div></section>`;
}

export function renderResults(content,period,branch="General"){
 const s=Store.summary(period,branch); const byCat=CONFIG.expenseCategories.map(c=>[c,rows('expenses',period,branch).filter(x=>x.category===c).reduce((a,x)=>a+Number(x.amount||0),0)]).filter(x=>x[1]);
 content.innerHTML=`<div class="profile-bar"><div><span class="section-kicker">RESULTADOS</span><b>${esc(branch)}</b><small>Ingresos, gastos, proveedores, inversiones y personal separados.</small></div><div class="profile-chips">${branchFilter(branch)}</div></div><div class="page-intro"><div><h2>Resultado mensual</h2><p>El resultado se calcula con la estructura real del negocio.</p></div><button class="secondary-button" data-pdf-close="results">Descargar PDF</button></div><div class="result-grid">${[['Ingresos',s.income,'good'],['Gastos operativos',s.totalExpenses,s.result>=0?'':'bad'],['Proveedores',s.providers,''],['Inversiones',s.investment,''],['Personal estimado',s.salary,''],['Resultado',s.result,s.result>=0?'good':'bad']].map(x=>`<div class="result-card"><span>${x[0]}</span><strong class="${x[2]}">${money(x[1])}</strong><p>${x[0]==='Resultado'?'Ingresos menos gastos operativos, inversión y costo estimado de horas.':''}</p></div>`).join('')}</div><section class="panel"><div class="panel-head"><div><span class="section-kicker">GASTOS</span><h3>Distribución por categoría</h3></div></div>${table(['Categoría','Monto','% de gastos'],byCat.map(([c,v])=>`<tr><td><b>${esc(c)}</b></td><td>${money(v)}</td><td>${s.totalExpenses?((v/s.totalExpenses)*100).toFixed(1):0}%</td></tr>`).join(''))}</section>`;
}

export function renderCompare(content,period,branch="General",compareA=prevPeriod(period),compareB=period){
 const periods=[...new Set([period,prevPeriod(period),...Store.db.periods.map(x=>x.id)])].sort().reverse();
 const calc=p=>Store.summary(p,branch); const a=calc(compareA),b=calc(compareB); const pct=(x,y)=>x===0?(y===0?0:100):((y-x)/Math.abs(x))*100; const line=(l,x,y)=>`<tr><td><b>${l}</b></td><td>${money(x)}</td><td>${money(y)}</td><td>${money(y-x)}</td><td class="${y-x>=0?'up':'down'}">${pct(x,y)>=0?'+':''}${pct(x,y).toFixed(1)}%</td></tr>`;
 content.innerHTML=`<div class="page-intro"><div><span class="section-kicker">COMPARATIVAS</span><h2>Comparación de períodos</h2><p>Elegí dos meses distintos; también podés ver la evolución de seis meses.</p></div><button class="secondary-button" data-pdf-close="compare">Descargar PDF</button></div><div class="compare-controls"><label>Período A<select data-compare-select="a">${periods.map(p=>`<option value="${p}" ${p===compareA?'selected':''}>${periodLabel(p)}</option>`).join('')}</select></label><span>vs.</span><label>Período B<select data-compare-select="b">${periods.map(p=>`<option value="${p}" ${p===compareB?'selected':''}>${periodLabel(p)}</option>`).join('')}</select></label></div><div class="profile-bar compact"><div><b>Perfil: ${esc(branch)}</b></div><div class="profile-chips">${branchFilter(branch)}</div></div>${table(['Indicador',periodLabel(compareA),periodLabel(compareB),'Diferencia','Variación'],[line('Ingresos',a.income,b.income),line('Gastos',a.totalExpenses,b.totalExpenses),line('Resultado',a.result,b.result),line('Proveedores',a.providers,b.providers),line('Inversiones',a.investment,b.investment),line('Horas',a.hours,b.hours)].join(''))}<section class="panel"><div class="panel-head"><div><span class="section-kicker">EVOLUCIÓN</span><h3>Últimos 6 meses desde ${periodLabel(compareB)}</h3></div></div><div class="bar-chart">${Array.from({length:6},(_,i)=>{const [y,m]=compareB.split('-').map(Number);const d=new Date(y,m-1-i,1),p=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,s=calc(p);return `<div class="bar-item"><div class="bar-track"><div class="bar-fill" style="height:${Math.min(100,Math.abs(s.result)/(Math.max(1,...Array.from({length:6},(_,j)=>{const dd=new Date(y,m-1-j,1),pp=`${dd.getFullYear()}-${String(dd.getMonth()+1).padStart(2,'0')}`;return Math.abs(calc(pp).result)})))*100)}%"></div></div><b>${p.slice(5)}</b><span>${money(s.result)}</span></div>`}).reverse().join('')}</div></section>`;
}

export function renderTasks(content){const all=Store.list('tasks').sort((a,b)=>`${a.dueDate} ${a.dueTime}`.localeCompare(`${b.dueDate} ${b.dueTime}`));const pending=all.filter(x=>x.status!=='completed'),done=all.filter(x=>x.status==='completed');content.innerHTML=`<div class="page-intro"><div><span class="section-kicker">CENTRO DE ATENCIÓN</span><h2>Recordatorios</h2><p>Las tareas viven dentro de Blunno. Completar una tarea también queda auditado.</p></div><button class="primary-button" data-new="task">＋ Nuevo recordatorio</button></div><div class="task-columns"><section class="panel"><h3>Pendientes</h3>${pending.map(t=>taskCard(t)).join('')||'<div class="empty-block">No hay tareas pendientes.</div>'}</section><section class="panel"><h3>Completadas</h3>${done.slice(0,20).map(t=>taskCard(t,true)).join('')||'<div class="empty-block">Todavía no hay tareas completadas.</div>'}</section></div>`}
function taskCard(t,done=false){return `<div class="task-card ${t.priority==='urgent'?'urgent':''}"><div><span class="priority ${t.priority}">${esc(t.priority||'normal')}</span><b>${esc(t.title)}</b><small>📅 ${dateLabel(t.dueDate)} ${esc(t.dueTime||'')} · 👤 ${esc(t.responsible)}</small></div>${done?`<div class="row-actions"><span class="status-pill success">REALIZADA</span><button class="danger-link" data-delete="tasks" data-id="${esc(t.id)}">Borrar</button></div>`:`<button class="primary-button" data-complete-task="${t.id}">✓ Realizada</button>`}</div>`}

export function renderAgent(content){
 const recent=Store.db.audit.filter(x=>x.collection!=='settings').slice(0,12); const person=localStorage.getItem('blunno-agent-person')||''; let history=[];try{history=JSON.parse(localStorage.getItem(`blunno-agent-chat-${person||'sin-usuario'}`)||'[]')}catch(e){} const messages=history.slice(-40).map(m=>`<div class="agent-message ${m.who==='user'?'user':'bot'}">${m.html}</div>`).join('');
 content.innerHTML=`<section class="agent-hero"><div><span class="hero-tag">AGENTE BLUNNO · CENTRO OPERATIVO</span><h2>Entiende, consulta y actúa con confirmación.</h2><p>Consulta caja, gastos, facturas, horas, resultados y cierre. Las modificaciones siempre muestran lo que se va a guardar y exigen confirmación.</p></div><div class="agent-badge">● CONFIRMACIÓN OBLIGATORIA</div></section>
 <section class="agent-grid"><div class="panel agent-chat"><div class="agent-statusbar"><span>Usuario actual</span><b id="agentCurrentPerson">${esc(person||'Elegir')}</b></div><div id="agentMessages" class="agent-messages">${messages||`<div class="agent-message bot"><b>Agente BLUNNO</b><span>¿Con quién estoy hablando?</span><div class="person-buttons">${CONFIG.responsiblePeople.map(p=>`<button data-agent-person="${p}">${p}</button>`).join('')}</div></div>`}</div><div class="agent-suggestions"><button data-agent-prompt="¿Cuánto gastamos este mes?">Resumen del mes</button><button data-agent-prompt="¿Qué facturas están cargadas?">Facturas cargadas</button><button data-agent-prompt="Prepará el cierre del mes">Preparar cierre</button><button data-agent-prompt="¿Cuántas horas cargamos?">Horas</button><button data-agent-prompt="¿Cuál es el saldo final de caja?">Saldo de caja</button></div><div class="agent-input"><input id="agentInput" placeholder="Escribí una consulta u orden…"><button id="agentMic" class="icon-button" title="Dictar">🎙</button><button id="agentSend" class="primary-button">Enviar</button></div></div><div class="panel"><span class="section-kicker">TRAZABILIDAD</span><h3>Actividad reciente</h3>${recent.map(x=>`<div class="activity"><div class="activity-dot"></div><div><b>${esc(x.action)}</b><span>${esc(x.responsible)} · ${dateTimeLabel(x.at)}</span></div></div>`).join('')||'<div class="empty-block">Sin actividad.</div>'}</div></section>`;
}

export function renderClose(content,period,branch="General"){
 if(branch==='General'){ content.innerHTML=`<div class="page-intro"><div><span class="section-kicker">CIERRE CONSOLIDADO</span><h2>General es una vista de consulta</h2><p>El cierre mensual se realiza por sucursal. En General podés consultar el estado consolidado sin crear ni modificar un cierre para una sucursal inexistente.</p></div></div><div class="close-summary">${CONFIG.branches.map(b=>{const s=Store.summary(period,b);const closed=Store.periodIsClosed(period,b);return `<div><span>${esc(b)}</span><b>${closed?'CERRADO':'ABIERTO'} · ${money(s.result)}</b></div>`}).join('')}</div>`; return; }
 const s=Store.summary(period,branch),closed=Store.periodIsClosed(period,branch);
 const versions=Store.db.closures.filter(x=>x.period===period&&x.branch===branch).sort((a,b)=>Number(b.version||0)-Number(a.version||0));
 const invoices=Store.list('invoices',period,branch), expenses=Store.list('expenses',period,branch), investments=Store.list('investments',period,branch), employees=Store.list('employees').filter(e=>e.active!==false&&(branch==='General'||e.branch===branch)), hours=Store.list('hours',period,branch);
 const late=invoices.filter(x=>String(x.loadDate||x.createdAt).slice(0,7)>period);
 const missingInvoice=invoices.filter(x=>!x.provider||!Number.isFinite(Number(x.amount))||!x.branch);
 const missingExpense=expenses.filter(x=>!x.category||!Number.isFinite(Number(x.amount))||!x.branch);
 const missingInvestment=investments.filter(x=>!x.concept||!Number.isFinite(Number(x.amount))||!x.branch);
 const noHours=employees.filter(e=>!hours.some(h=>h.employeeId===e.id));
 const noLiquidation=employees.filter(e=>hours.some(h=>h.employeeId===e.id)&&!Store.list('liquidations',period,branch).some(l=>l.employeeId===e.id));
 const checklist=[
  ['Caja diaria',true,`${s.cashCount} movimientos · resto final ${money(s.cashFinal)}`],
  ['Ingresos',true,`${Store.list('incomes',period,branch).length} movimientos · ${money(s.income)}`],
  ['Proveedores / facturas',missingInvoice.length===0,`${s.invoiceCount} facturas · ${missingInvoice.length?missingInvoice.length+' requieren revisión':'sin datos obligatorios faltantes'}`],
  ['Gastos del local',missingExpense.length===0,`${s.expenseCount} gastos · ${missingExpense.length?missingExpense.length+' requieren revisión':'controlados'}`],
  ['Inversiones',missingInvestment.length===0,`${s.investmentCount} inversiones · ${missingInvestment.length?missingInvestment.length+' requieren revisión':'controladas'}`],
  ['Horas',noHours.length===0,`${number(s.hours)} horas · ${noHours.length?noHours.length+' empleados sin carga':'carga registrada'}`],
  ['Liquidaciones',noLiquidation.length===0,`${s.liquidationCount} liquidaciones vigentes · ${noLiquidation.length?noLiquidation.length+' empleados pendientes':'sin pendientes'}`],
  ['Facturas posteriores al cierre',late.length===0,late.length?`${late.length} factura(s) cargada(s) después del período`:'No se detectaron cargas posteriores'],
  ['Período abierto',!closed,closed?'Ya existe un cierre vigente':'Listo para cerrar']
 ];
 const blockers=checklist.filter(x=>!x[1]);
 content.innerHTML=`<div class="profile-bar"><div><span class="section-kicker">CIERRE MENSUAL CONTROLADO</span><b>${esc(branch)}</b><small>El cierre es manual y versionado. Las correcciones posteriores quedan como una nueva versión.</small></div><div class="profile-chips">${branchFilter(branch)}</div></div>
 <div class="close-status ${closed?'closed':'open'}"><div><span>ESTADO</span><strong>${closed?'CERRADO':'ABIERTO'}</strong></div><div><span>VERSIÓN ACTUAL</span><strong>${versions[0]?.version||0}</strong></div><div><span>RESULTADO</span><strong>${money(s.result)}</strong></div><div><span>RESPONSABLE</span><strong>${esc(versions[0]?.responsible||'Sin cerrar')}</strong></div></div>
 <section class="panel"><div class="panel-head"><div><span class="section-kicker">CENTRO DE CONTROL MENSUAL</span><h3>Estado del período</h3></div>${closed?'<button class="secondary-button" data-reopen-period="1">Reabrir con motivo</button>':'<button class="primary-button" data-close-period="1" '+(blockers.length?'disabled title="Hay controles bloqueantes pendientes"':'')+'>Cerrar y generar PDF</button>'}</div><div class="close-check-grid">${checklist.map(([name,ok,detail])=>`<div class="close-check ${ok?'ok':'block'}"><div class="check-icon">${ok?'✓':'!'}</div><div><b>${esc(name)}</b><span>${esc(detail)}</span></div><strong>${ok?'OK':'REVISAR'}</strong></div>`).join('')}</div>${blockers.length?`<div class="notice danger-box">Hay ${blockers.length} controles que requieren revisión antes de cerrar.</div>`:'<div class="notice success">✓ El control previo no encontró bloqueos.</div>'}</section>
 <section class="panel"><div class="panel-head"><div><span class="section-kicker">FOTOGRAFÍA</span><h3>Totales del cierre</h3></div></div><div class="close-summary"><div><span>Ingresos</span><b>${money(s.income)}</b></div><div><span>Gastos del local</span><b>${money(s.localExpense)}</b></div><div><span>Proveedores</span><b>${money(s.providers)}</b></div><div><span>Inversiones</span><b>${money(s.investment)}</b></div><div><span>Personal</span><b>${money(s.salary)}</b></div><div><span>Resultado</span><b>${money(s.result)}</b></div><div><span>Caja diaria</span><b>Separada</b></div></div></section>
 <section class="panel"><div class="panel-head"><div><span class="section-kicker">VERSIONES DEL CIERRE</span><h3>Historial completo</h3></div></div>${versions.map(v=>`<div class="version-row"><div><b>Versión ${v.version}</b><span>${dateTimeLabel(v.closedAt)} · ${esc(v.responsible)} · ${esc(v.status)}</span></div><strong>${money(v.summary?.result)}</strong><button class="secondary-button" data-close-version="${v.id}">PDF</button></div>`).join('')||'<div class="empty-block">Todavía no hay cierres registrados.</div>'}</section>`;
}

export function renderFiles(content,period,branch="General"){
 const allFiles=Store.list('files').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));
 const files=allFiles.filter(f=>branch==='General'||f.branch===branch);
 const groups=new Map();
 for(const f of files){const dt=String(f.period||period), year=dt.slice(0,4)||'Sin año', month=dt.slice(5,7)||'00', key=`${year}|${month}|${f.branch||'General'}|${f.sector||'Documento'}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(f);}
 const groupHtml=[...groups.entries()].map(([key,items])=>{const [year,month,b,se]=key.split('|');return `<details class="file-folder" open><summary><span>📁 ${esc(year)} / ${esc(periodLabel(`${year}-${month}`))} / ${esc(b)} / ${esc(se)}</span><b>${items.length}</b></summary><div class="file-grid">${items.map(f=>{const integrity=Store.fileIntegrity(f);return `<article class="file-card"><div class="file-type">📄 ${esc(f.mime||'PDF')}</div><h3>${esc(f.name)}</h3><p>${esc(f.sector||'Documento')} · ${esc(f.branch||'General')} · ${periodLabel(f.period||period)}</p><div class="file-meta"><span>Generado: ${dateTimeLabel(f.createdAt)}</span><span>Responsable: ${esc(f.responsible||'—')}</span><span>Versión: ${esc(f.version||1)}</span><span>Ruta: ${esc(f.storagePath||'local/archivos')}</span></div><div class="file-integrity ${integrity.status==='ok'?'ok':integrity.status==='anterior'?'warning':'neutral'}">${integrity.status==='ok'?'✓ Integridad vigente':integrity.status==='anterior'?'⚠ Documento anterior al último cambio':'• Sin comparación de origen'}</div><div class="row-actions"><button class="secondary-button" data-view-file="${esc(f.id)}">Ver</button><button class="primary-button" data-download-file="${esc(f.id)}">Descargar</button><button class="secondary-button" data-print-file="${esc(f.id)}">Imprimir</button><button class="danger-link" data-delete="files" data-id="${esc(f.id)}">Papelera</button></div></article>`}).join('')}</div></details>`}).join('')||'<div class="empty-block">No hay documentos para este contexto.</div>';
 content.innerHTML=`<div class="page-intro"><div><span class="section-kicker">REPOSITORIO DOCUMENTAL</span><h2>Archivos</h2><p>Organizados por año, mes, sucursal y sector. Cada archivo conserva ficha documental, versión, ubicación e integridad.</p></div><button class="secondary-button" data-view-jump="import">Importar / backup</button></div><div class="file-filters"><span>${files.length} documentos visibles</span><span>${allFiles.length} documentos en el repositorio local</span><span>Perfil: ${esc(branch)} · ${periodLabel(period)}</span></div>${groupHtml}`;
}

export function renderHistory(content){
 const data=Store.db.audit;
 content.innerHTML=`<div class="page-intro"><div><span class="section-kicker">AUDITORÍA PERMANENTE</span><h2>Historial y trazabilidad</h2><p>Fecha, hora, minuto, responsable, sector, sucursal, período, acción, registro afectado y antes/después. La auditoría no se elimina.</p></div><button class="secondary-button" id="exportAudit">Exportar auditoría</button><button class="secondary-button" data-pdf-close="history">PDF</button></div>${table(['Fecha / hora','Acción','Sector','Sucursal','Período','Responsable','Registro','Cambios'],data.map(x=>`<tr><td>${dateTimeLabel(x.at)}</td><td><span class="audit-action">${esc(x.action)}</span></td><td>${esc(x.sector||x.collection)}</td><td>${esc(x.branch||'—')}</td><td>${x.period?esc(periodLabel(x.period)):'—'}</td><td>${esc(x.responsible||'—')}</td><td>${esc(x.collection)} · ${esc(x.recordId)}</td><td><details><summary>Ver</summary><pre class="audit-pre">${esc(JSON.stringify({antes:x.before,despues:x.after},null,2))}</pre></details></td></tr>`).join(''))}`;
}

export function renderTrash(content){
 const data=Store.trash().sort((a,b)=>String(b.deletedAt).localeCompare(String(a.deletedAt)));
 content.innerHTML=`<div class="page-intro"><div><span class="section-kicker">PAPELERA SEGURA</span><h2>Elementos eliminados</h2><p>Los registros permanecen 30 días. Podés seleccionar varios para restaurarlos o eliminarlos definitivamente. La eliminación definitiva también queda auditada.</p></div></div>
 <div class="trash-toolbar"><div><b>${data.length}</b><span> elementos en papelera</span></div><div><button class="secondary-button" id="trashRestoreSelected" ${data.length?'':'disabled'}>↶ Restaurar seleccionados</button><button class="danger-button" id="trashPurgeSelected" ${data.length?'':'disabled'}>Eliminar definitivamente</button><button class="danger-link" id="trashEmpty" ${data.length?'':'disabled'}>Vaciar papelera</button></div></div>
 ${table(['<input type="checkbox" id="trashSelectAll">','Sector','Registro','Eliminado','Responsable','Vence','Acciones'],data.map(x=>{const expires=new Date(new Date(x.deletedAt).getTime()+30*86400000);return `<tr><td><input type="checkbox" class="trash-select" data-collection="${esc(x._collection)}" data-id="${esc(x.id)}"></td><td>${esc(x._collection)}</td><td><b>${esc(x.name||x.concept||x.title||x.provider||x.id)}</b></td><td>${dateTimeLabel(x.deletedAt)}</td><td>${esc(x.responsible||'—')}</td><td>${dateTimeLabel(expires.toISOString())}</td><td><button class="secondary-button" data-restore="${esc(x._collection)}" data-id="${esc(x.id)}">Restaurar</button><button class="danger-link" data-purge="${esc(x._collection)}" data-id="${esc(x.id)}">Eliminar</button></td></tr>`}).join(''))}`;
}

export function renderImport(content){content.innerHTML=`<div class="page-intro"><div><span class="section-kicker">EXCEL / RESPALDOS</span><h2>Importar, exportar y sincronizar</h2><p>Excel puede seguir siendo la herramienta diaria. La web registra la importación con origen, responsable y cambios.</p></div></div><div class="import-grid"><section class="panel"><span class="section-kicker">PLANIFICACIÓN</span><h3>Sincronizar Excel de horas</h3><p>Reconoce hojas por empleado y fechas. Si un dato no puede interpretarse, queda para revisión: no se inventa información.</p><input id="excelInput" type="file" accept=".xlsx,.xls,.csv" class="file-input"><div id="importPreview"></div></section><section class="panel"><span class="section-kicker">RESPALDOS</span><h3>Seguridad</h3><p>Generá una copia completa o restaurá un respaldo después de confirmarlo. Los documentos guardados localmente también forman parte del paquete.</p><div class="backup-actions"><button class="secondary-button" id="backupZipButton">Descargar backup completo ZIP</button><button class="secondary-button" id="backupButton">Descargar datos JSON</button><button class="secondary-button" id="exportExcelButton">Exportar Excel Blunno</button><label class="secondary-button file-button-label">Restaurar datos JSON<input id="backupRestoreInput" type="file" accept=".json,application/json" hidden></label></div></section></div><section class="panel"><span class="section-kicker">SINCRONIZACIÓN REAL</span><h3>Control doble</h3><p>El navegador no puede vigilar silenciosamente un archivo local de Windows. Esta versión evita duplicados mediante una clave de origen; para sincronización automática permanente se puede conectar una fuente documental externa.</p></section>`}

export function renderPeriodModal(){return Store.db.periods.slice().sort((a,b)=>String(b.id).localeCompare(String(a.id)));}
export function renderView(view,content,period,branch="General",compareA=prevPeriod(period),compareB=period){
 const map={dashboard:renderDashboard,income:renderIncome,cash:renderCash,providers:renderProviders,invoices:renderInvoices,expenses:renderExpenses,investments:renderInvestments,people:renderPeople,hours:renderHours,results:renderResults,compare:renderCompare,tasks:renderTasks,agent:renderAgent,close:renderClose,files:renderFiles,history:renderHistory,trash:renderTrash,import:renderImport};
 if(view==="compare") return renderCompare(content,period,branch,compareA,compareB);
 (map[view]||renderDashboard)(content,period,branch);
}
